/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AsinDto { 
    ninId?: number;
    lga?: number;
    area?: number;
    streetName?: string;
    houseNumber?: string;
    landMark?: string;
    name?: string;
    phoneNumber?: string;
    asin?: string;
    date?: string;
    address?: string;
    photo?: string;
    dateCreated?: string;
    email?: string;
    firstname?: string;
    lastname?: string;
    othernames?: string;
    dob?: string;
    gender?: string;
    employmentStatus?: string;
    middleName?: string;
    maritalStatus?: string;
    nin?: string;
    profession?: string;
    surname?: string;
    telePhoneNumber?: string;
    type?: string;
}

