/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CardDto { 
    id?: number;
    name?: string;
    tin?: string;
    dateCreated?: string;
    status?: CardDto.StatusEnum;
    type?: CardDto.TypeEnum;
    line?: string;
    plateNumber?: string;
    typeName?: string;
    address?: string;
    phoneNumber?: string;
    photo?: string;
    email?: string;
}
export namespace CardDto {
    export type StatusEnum = 'PRINTED' | 'NOT_PRINTED' | 'NOT_PAID' | 'UPDATED';
    export const StatusEnum = {
        Printed: 'PRINTED' as StatusEnum,
        NotPrinted: 'NOT_PRINTED' as StatusEnum,
        NotPaid: 'NOT_PAID' as StatusEnum,
        Updated: 'UPDATED' as StatusEnum
    };
    export type TypeEnum = 'TRANSPORT' | 'MARKET' | 'ENUMERATION' | 'PROPERTY' | 'CORPORATE' | 'MARKET_STICKER' | 'TRANSPORT_STICKER';
    export const TypeEnum = {
        Transport: 'TRANSPORT' as TypeEnum,
        Market: 'MARKET' as TypeEnum,
        Enumeration: 'ENUMERATION' as TypeEnum,
        Property: 'PROPERTY' as TypeEnum,
        Corporate: 'CORPORATE' as TypeEnum,
        MarketSticker: 'MARKET_STICKER' as TypeEnum,
        TransportSticker: 'TRANSPORT_STICKER' as TypeEnum
    };
}


