/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortalUser } from './portal-user';


export interface Corperate { 
    id?: number;
    dateDeactivated?: string;
    status?: Corperate.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    lga?: number;
    area?: number;
    state?: string;
    corperateName?: string;
    rcNumber?: string;
    companyType?: string;
    phonenumber?: string;
    email?: string;
    address?: string;
    street?: string;
    landmark?: string;
    companyJob?: string;
    companyWork?: string;
    portalUser?: PortalUser;
    timeCreated?: string;
    timeUpdated?: string;
    tinNumber?: string;
}
export namespace Corperate {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


