/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CroReportPojo { 
    name?: string;
    marketEnumerations?: number;
    transportEnumerations?: number;
    dateCreated?: string;
    transportPayments?: number;
    numberOfPaidMarket?: number;
    numberOfPaidTransport?: number;
    shopPayments?: number;
}

