/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmblemStockPojo { 
    id?: number;
    type?: EmblemStockPojo.TypeEnum;
    dateCreated?: string;
    quantity?: number;
    numberIssued?: number;
    createdBy?: string;
    year?: string;
}
export namespace EmblemStockPojo {
    export type TypeEnum = 'MOTORCYCLES' | 'TRICYCLE' | 'TAXI' | 'BUSES' | 'PICKUP' | 'TRUCKS_LORRIES';
    export const TypeEnum = {
        Motorcycles: 'MOTORCYCLES' as TypeEnum,
        Tricycle: 'TRICYCLE' as TypeEnum,
        Taxi: 'TAXI' as TypeEnum,
        Buses: 'BUSES' as TypeEnum,
        Pickup: 'PICKUP' as TypeEnum,
        TrucksLorries: 'TRUCKS_LORRIES' as TypeEnum
    };
}


