/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmblemListPojo { 
    id?: number;
    type?: EmblemListPojo.TypeEnum;
    number?: string;
    dateCreated?: string;
    createdBy?: string;
    issued?: boolean;
    printStatus?: EmblemListPojo.PrintStatusEnum;
}
export namespace EmblemListPojo {
    export type TypeEnum = 'MOTORCYCLES' | 'TRICYCLE' | 'TAXI' | 'BUSES' | 'PICKUP' | 'TRUCKS_LORRIES';
    export const TypeEnum = {
        Motorcycles: 'MOTORCYCLES' as TypeEnum,
        Tricycle: 'TRICYCLE' as TypeEnum,
        Taxi: 'TAXI' as TypeEnum,
        Buses: 'BUSES' as TypeEnum,
        Pickup: 'PICKUP' as TypeEnum,
        TrucksLorries: 'TRUCKS_LORRIES' as TypeEnum
    };
    export type PrintStatusEnum = 'PRINTED' | 'NOT_PRINTED' | 'NOT_PAID' | 'UPDATED';
    export const PrintStatusEnum = {
        Printed: 'PRINTED' as PrintStatusEnum,
        NotPrinted: 'NOT_PRINTED' as PrintStatusEnum,
        NotPaid: 'NOT_PAID' as PrintStatusEnum,
        Updated: 'UPDATED' as PrintStatusEnum
    };
}


