/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    firstName?: string;
    lastName?: string;
    image?: string;
    token?: string;
    role?: string;
    permissions?: Array<LoginResponse.PermissionsEnum>;
    username?: string;
    id?: number;
    userVerified?: boolean;
}
export namespace LoginResponse {
    export type PermissionsEnum = 'CREATE_USER' | 'UPDATE_USER' | 'CREATE_MARKET' | 'CREATE_TRANSPORT' | 'CREATE_PROPERTY' | 'PRINT_CARD' | 'MANAGE_DRIVER' | 'ENROLLMENT' | 'DEFAULT' | 'SIGNAGE' | 'CAN_VIEW_TOKEN' | 'CAN_ACCESS_INFORMAL_SECTOR' | 'CAN_ACCESS_EMBLEM_MANAGEMENT' | 'CAN_VIEW_TRANSPORT_REPORT' | 'CAN_VIEW_MARKET_REPORT' | 'CAN_VIEW_TRANSPORT' | 'CAN_VIEW_MARKET' | 'CAN_VIEW_PROPERTY' | 'CAN_VIEW_PAYMENTS' | 'CAN_DELETE_DRIVER' | 'CAN_DELETE_TRANSPORT' | 'CAN_GENERATE_EMBLEM' | 'CAN_PRINT_EMBLEM' | 'CAN_VIEW_EMBLEM' | 'CAN_ISSUE_EMBLEM';
    export const PermissionsEnum = {
        CreateUser: 'CREATE_USER' as PermissionsEnum,
        UpdateUser: 'UPDATE_USER' as PermissionsEnum,
        CreateMarket: 'CREATE_MARKET' as PermissionsEnum,
        CreateTransport: 'CREATE_TRANSPORT' as PermissionsEnum,
        CreateProperty: 'CREATE_PROPERTY' as PermissionsEnum,
        PrintCard: 'PRINT_CARD' as PermissionsEnum,
        ManageDriver: 'MANAGE_DRIVER' as PermissionsEnum,
        Enrollment: 'ENROLLMENT' as PermissionsEnum,
        Default: 'DEFAULT' as PermissionsEnum,
        Signage: 'SIGNAGE' as PermissionsEnum,
        CanViewToken: 'CAN_VIEW_TOKEN' as PermissionsEnum,
        CanAccessInformalSector: 'CAN_ACCESS_INFORMAL_SECTOR' as PermissionsEnum,
        CanAccessEmblemManagement: 'CAN_ACCESS_EMBLEM_MANAGEMENT' as PermissionsEnum,
        CanViewTransportReport: 'CAN_VIEW_TRANSPORT_REPORT' as PermissionsEnum,
        CanViewMarketReport: 'CAN_VIEW_MARKET_REPORT' as PermissionsEnum,
        CanViewTransport: 'CAN_VIEW_TRANSPORT' as PermissionsEnum,
        CanViewMarket: 'CAN_VIEW_MARKET' as PermissionsEnum,
        CanViewProperty: 'CAN_VIEW_PROPERTY' as PermissionsEnum,
        CanViewPayments: 'CAN_VIEW_PAYMENTS' as PermissionsEnum,
        CanDeleteDriver: 'CAN_DELETE_DRIVER' as PermissionsEnum,
        CanDeleteTransport: 'CAN_DELETE_TRANSPORT' as PermissionsEnum,
        CanGenerateEmblem: 'CAN_GENERATE_EMBLEM' as PermissionsEnum,
        CanPrintEmblem: 'CAN_PRINT_EMBLEM' as PermissionsEnum,
        CanViewEmblem: 'CAN_VIEW_EMBLEM' as PermissionsEnum,
        CanIssueEmblem: 'CAN_ISSUE_EMBLEM' as PermissionsEnum
    };
}


