/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManifestForm { 
    id?: number;
    dateDeactivated?: string;
    status?: ManifestForm.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    nameOfTransport?: string;
    nameOfDriver?: string;
    plateNumber?: string;
    firstName?: string;
    lastName?: string;
    middleName?: string;
    address?: string;
    phoneNumber?: string;
    mobileNumber?: string;
    email?: string;
    gender?: string;
    bloodGroup?: string;
    nameOfNextOfKin?: string;
    numberOfNextOfKin?: string;
    addressOfNextOfKin?: string;
    destination?: string;
}
export namespace ManifestForm {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


