/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarketEnumDTO { 
    market?: number;
    marketName?: string;
    lineName?: string;
    cityName?: string;
    lgaName?: string;
    category?: string;
    phoneNumber?: string;
    paymentMode?: string;
    lga?: number;
    city?: string;
    shopNumber?: string;
    firstName?: string;
    lastName?: string;
    otherNames?: string;
    address?: string;
    email?: string;
    photo?: string;
    asin?: string;
    nin?: string;
    residentialTown?: string;
    resididentiallga?: number;
    line?: number;
    tinNumebr?: string;
    area?: number;
}

