/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NIN { 
    id?: number;
    birthCountry?: string;
    dob?: string;
    birthDate?: string;
    birthLGA?: string;
    birthState?: string;
    centralId?: number;
    educationalLevel?: string;
    email?: string;
    gender?: string;
    employmentStatus?: string;
    firstName?: string;
    middleName?: string;
    height?: number;
    maritalStatus?: string;
    nin?: string;
    nokAddress?: string;
    nokAddress2?: string;
    nokFirstName?: string;
    nokLGA?: string;
    nokState?: string;
    nokSurname?: string;
    nokTown?: string;
    nspokenLang?: string;
    photo?: string;
    photoFileCode?: string;
    profession?: string;
    religion?: string;
    residenceAddressLine1?: string;
    residenceTown?: string;
    residenceLga?: string;
    residenceState?: string;
    residenceStatus?: string;
    selfOriginLga?: string;
    selfOriginPlace?: string;
    selfOriginState?: string;
    signature?: string;
    signatureFileCode?: string;
    surname?: string;
    telePhoneNumber?: string;
    title?: string;
    dateCreated?: string;
    dateUpdated?: string;
    asin?: string;
}

