/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    paymentReference?: string;
    asin?: string;
    status?: NotificationDto.StatusEnum;
    amount?: number;
    code?: string;
    date?: string;
    description?: string;
}
export namespace NotificationDto {
    export type StatusEnum = 'PENDING' | 'APPROVED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum
    };
}


