/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OccupantDto { 
    id?: number;
    firstName?: string;
    lastName?: string;
    address?: string;
    others?: string;
    phoneNumber?: string;
    more?: string;
    asin?: string;
    occupantType?: string;
    residentType?: string;
    premisesId?: number;
    presumptiveId?: number;
    wasteId?: number;
    fireId?: number;
    signageId?: number;
    property?: number;
    subsignageId?: number;
    subfireId?: number;
    subwasteId?: number;
    subpremisesId?: number;
    subpresumptiveId?: number;
}

