/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentHistory { 
    id?: number;
    dateDeactivated?: string;
    status?: PaymentHistory.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    asin?: string;
    paymentReference?: string;
    code?: string;
    amount?: number;
    payment_date?: string;
    paymentStatus?: PaymentHistory.PaymentStatusEnum;
    feeDescription?: string;
    inEmblemWallet?: boolean;
}
export namespace PaymentHistory {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
    export type PaymentStatusEnum = 'PENDING' | 'APPROVED';
    export const PaymentStatusEnum = {
        Pending: 'PENDING' as PaymentStatusEnum,
        Approved: 'APPROVED' as PaymentStatusEnum
    };
}


