/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZonalOffice } from './zonal-office';
import { Roles } from './roles';


export interface PortalUser { 
    id?: number;
    dateDeactivated?: string;
    status?: PortalUser.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    firstName?: string;
    lastName?: string;
    otherNames?: string;
    email?: string;
    phoneNumber?: string;
    generatedPassword?: string;
    username?: string;
    dateOfBirth?: string;
    displayName?: string;
    gender?: PortalUser.GenderEnum;
    setupComplete?: boolean;
    emailVerified?: boolean;
    preferredName?: string;
    userVerified?: boolean;
    nationalIdentificationNumber?: string;
    image?: string;
    stateId?: number;
    role?: Roles;
    address?: string;
    office?: ZonalOffice;
}
export namespace PortalUser {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
    export type GenderEnum = 'MALE' | 'FEMALE';
    export const GenderEnum = {
        Male: 'MALE' as GenderEnum,
        Female: 'FEMALE' as GenderEnum
    };
}


