/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropertyDto { 
    houseNumber?: string;
    type?: string;
    category?: string;
    floors?: string;
    area?: number;
    street?: number;
    id?: number;
    streetName?: string;
    areaId?: number;
    streetsId?: number;
    pid?: string;
    cat?: number;
    typeId?: number;
}

