/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuildingType } from './building-type';
import { BuildingCategory } from './building-category';
import { Street } from './street';
import { LgaAreas } from './lga-areas';


export interface Property { 
    id?: number;
    dateDeactivated?: string;
    status?: Property.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    houseNumber?: string;
    type?: BuildingType;
    category?: BuildingCategory;
    floors?: string;
    apartment?: string;
    pid?: string;
    area?: LgaAreas;
    street?: Street;
}
export namespace Property {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


