/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropertyPojo { 
    street?: string;
    houseNumber?: string;
    category?: string;
    lga?: string;
    area?: string;
    type?: string;
    occupants?: number;
    pid?: string;
    apartments?: string;
    dateCreated?: string;
}

