/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShopOwnerDto { 
    name?: string;
    business?: string;
    phone?: string;
    email?: string;
    address?: string;
    photo?: string;
    tinnumber?: string;
    lastname?: string;
    firstname?: string;
    middlename?: string;
    nin?: string;
    asin?: string;
    line?: string;
    shop?: string;
    type?: string;
    busnessName?: string;
    businessType?: string;
    ownership?: string;
}

