/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tin } from './tin';
import { Markets } from './markets';
import { Lines } from './lines';


export interface Shop { 
    id?: number;
    dateDeactivated?: string;
    status?: Shop.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    shop_number?: string;
    number_of_occupants?: number;
    paymentMode?: string;
    market?: Markets;
    line?: Lines;
    tin?: Tin;
}
export namespace Shop {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


