/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Tin { 
    id?: number;
    tinNumber?: string;
    tinType?: Tin.TinTypeEnum;
    tinStatus?: Tin.TinStatusEnum;
    timeCreated?: string;
    timeUpdated?: string;
}
export namespace Tin {
    export type TinTypeEnum = 'MARKET' | 'TRANSPORT' | 'STATE' | 'PROPERTY' | 'INDIVIDUAL' | 'CORPERATE';
    export const TinTypeEnum = {
        Market: 'MARKET' as TinTypeEnum,
        Transport: 'TRANSPORT' as TinTypeEnum,
        State: 'STATE' as TinTypeEnum,
        Property: 'PROPERTY' as TinTypeEnum,
        Individual: 'INDIVIDUAL' as TinTypeEnum,
        Corperate: 'CORPERATE' as TinTypeEnum
    };
    export type TinStatusEnum = 'ACTIVE' | 'IN_ACTIVE';
    export const TinStatusEnum = {
        Active: 'ACTIVE' as TinStatusEnum,
        InActive: 'IN_ACTIVE' as TinStatusEnum
    };
}


