/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserDemographicIndividual { 
    id?: number;
    user?: User;
    bvn?: string;
    firstname?: string;
    lastname?: string;
    phoneNumber?: string;
    gender?: UserDemographicIndividual.GenderEnum;
    address?: string;
    city?: string;
    lgaId?: number;
    legacy?: boolean;
    stateId?: number;
    photo?: string;
    lga?: number;
    area?: number;
    houseNumber?: string;
    landMark?: string;
    name?: string;
    asin?: string;
    dateCreated?: string;
    email?: string;
    middlename?: string;
}
export namespace UserDemographicIndividual {
    export type GenderEnum = 'MALE' | 'FEMALE';
    export const GenderEnum = {
        Male: 'MALE' as GenderEnum,
        Female: 'FEMALE' as GenderEnum
    };
}


