/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NIN } from './nin';
import { PortalUser } from './portal-user';


export interface User { 
    id?: number;
    dateDeactivated?: string;
    status?: User.StatusEnum;
    createdAt?: string;
    lastUpdatedAt?: string;
    portalUser?: PortalUser;
    nin?: NIN;
    streetname?: string;
    houseNumber?: string;
    landmark?: string;
    timeCreated?: string;
    timeUpdated?: string;
}
export namespace User {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
}


