/**
 * ANAMBRA API
 * The ANAMBRA RESTful service using springdoc-openapi and OpenAPI 3.0
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cuhuegbulem@oasismgt.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    firstName?: string;
    lastName?: string;
    phoneNumber?: string;
    address?: string;
    photo?: string;
    email?: string;
    lga?: number;
    area?: number;
    nin?: string;
    password?: string;
    role?: string;
    zonalOffice?: number;
}

